blog/blog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls import url
#from store import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
    #url(r'^$', views.index),
]

blog/store/urls.py
from django.urls import path 


from . import views # import views so we can use them in urls.

app_name='predict'


urlpatterns = [

    path('', views.predict , name ='predict'), #will call the method "index" in "views.py"
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

blog/store/models.py
from django.db import models

# Create your models here.

class PredResults(models.Model):
    
    sepal_length = models.FloatField()
    sepal_width = models.FloatField()
    petal_length = models.FloatField()
    petal_width = models.FloatField()
    classification = models.CharField(max_length=30)
    score = models.FloatField()


    def __str__(self):
        return self.classification

blog/store/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults
# Create your views here.

#from django.http import HttpResponse


#def index(request):

    #message = "Salut tout le monde !"

    #return HttpResponse(message)

def predict(request):

    return render(request , 'predict.html')

def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        sepal_length = float(request.POST.get('sepal_length'))
        sepal_width = float(request.POST.get('sepal_width'))
        petal_length = float(request.POST.get('petal_length'))
        petal_width = float(request.POST.get('petal_width'))

        # from pandas import read_csv
        # from sklearn.model_selection import train_test_split
        # from sklearn.svm import SVC
        # import pandas as pd
        # from sklearn.metrics import accuracy_score

        # iris = pd.read_csv("/home/fadwa/Downloads/iris.csv")
        # df=iris
        # X = df.drop('variety', axis=1)
        # y = df['variety']

        # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=99)
        # model = SVC(gamma='auto')
        # model.fit(X_train, y_train)
        # predictions = model.predict(X_test)

        # score = accuracy_score(y_test, predictions)
        
        # Unpickle model
        # model= pd.read_pickle(r'/home/fadwa/Downloads/new_model.pickle')
        # # Make prediction
        # result = model.predict([[sepal_length, sepal_width, petal_length, petal_width]])
        # classification = result[0]

        import numpy as np
        from sklearn.datasets import load_iris
        from sklearn.model_selection import train_test_split
        from sklearn.preprocessing import OneHotEncoder
        from keras.models import Sequential
        from keras.layers import Dense
        from keras.optimizers import Adam

        iris_data = load_iris() # load the iris dataset
        x = iris_data.data
        y = iris_data.target # Convert data to a single column
        z = iris_data.target_names

        train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

        model = Sequential()
        model.add(Dense(100, input_shape=(4,), activation='relu'))
        model.add(Dense(100, activation='relu'))
        model.add(Dense(100, activation='relu', name='fc1'))
        model.add(Dense(3, activation='softmax', name='output'))
        model.compile(optimizer= 'Adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
        model.fit(train_x, train_y,verbose=2, batch_size=30, epochs=350)

        results = model.evaluate(test_x, test_y)
        score = results[1]
        scorepr = score *100
        scorepr = format(scorepr, ".2f")
        result = model.predict([[sepal_length, sepal_width, petal_length, petal_width]])
        predicted = np.argmax(result,axis=1)
        classification = z[predicted[0]]


        PredResults.objects.create(sepal_length=sepal_length, sepal_width=sepal_width, petal_length=petal_length,
                                   petal_width=petal_width, classification=classification,score=scorepr)

        
        return JsonResponse({'result': classification, 'sepal_length': sepal_length,
                             'sepal_width': sepal_width, 'petal_length': petal_length, 'petal_width': petal_width,'score':score},
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)

blog/store/templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
   <link rel="icon" href="data:;base64,iVBORw0KGgo=">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   
    <link rel="stylesheet"  href="{%  static  'css/style.css'  %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <title>Iris prediction</title>
    </head>

    <body >

    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="Nav">
    
        <div id="nav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Iris Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">Data Base Iris</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

blog/store/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" id="head">
            <div id="H">
                <h5 class="modal-title" id="exampleModalLabel">The Prediction Results</h5>
                
            </div>
            <div class="modal-body" >
                <h5>Prediction Input:</h5>
                <div id="txt">Sepal Length : <span id="sl"></span></div>
                <div id="txt">Sepal Width : <span id="sw"></span></div>
                <div id="txt">Petal Length : <span id="pl"></span></div>
                <div id="txt">Petal width : <span id="pw"></span></div>
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
                <h5 class="pt-4"> Deep Learning Accuracy Score %:</h5>
                <div id="score"></div>

            </div>
            <div class="modal-footer">
               
                <a  class="buttonV" href="/results" role="button">View Data Base</a>
                 <button type="button" class="buttonC" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div  id="global">
    <div class="row justify-content-md-center">
        <div class="col-md-4" id="first">
            <p>Iris Prediction</p><br>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="sepal_length">Sepal Length</label>
                    <input type="number" step="0.1" class="form-number" id="sepal_length" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Sepal Width">Sepal Width</label>
                    <input type="number" step="0.1" class="form-number" id="sepal_width" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="petal_length">Petal Length</label>
                    <input type="number" step="0.1" class="form-number" id="petal_length" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="petal_width">Petal Width</label>
                    <input type="number" step="0.1" class="form-number" id="petal_width" placeholder="" required>
                </div><br>
                <button type="submit" value="Submit" class="button" data-toggle="modal" data-target="#exampleModal">Predict Type</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                sepal_length:$('#sepal_length').val(),
                sepal_width:$('#sepal_width').val(),
                petal_length:$('#petal_length').val(),
                petal_width:$('#petal_width').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['sepal_length']
                document.getElementById("sw").innerHTML = json['sepal_width']
                document.getElementById("pl").innerHTML = json['petal_length']
                document.getElementById("pw").innerHTML = json['petal_width']
                document.getElementById("score").innerHTML = json['score']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })

</script>

{% endblock %}

blog/store/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5" id="tab">
        <div class="row">

        <h1>Prediction Results</h1><br>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Sepal length</th>
                <th scope="col">Sepal width</th>
                <th scope="col">Petal length</th>
                <th scope="col">Petal width</th>
                <th scope="col">Prediction</th>
                <th scope="col">Score</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.sepal_length }}</td>
                    <td>{{ data.sepal_width }}</td>
                    <td>{{ data.petal_length }}</td>
                    <td>{{ data.petal_width }}</td>
                    <td>{{ data.classification }}</td>
                    <td>{{ data.score}}%</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}